[feature] WPN-166 - Upgrade PHP and WordPress version
epfl-si/wp-gutenberg-epfl pull request #416
Opened 2024-11-13 16:16 UTC by rosamaggi

- PHP: 8.1
- Wordpress: 6.6.2

Fix some bugs:
- specify function return type
- create variables before using them
- delete deprecated field `multiline="p"` in RichText

2024-11-13 18:27 UTC, ponsfrilus approved these changes
👍

2024-12-04 17:48 UTC, ponsfrilus commented on frontend/epfl-people/templates/dynamic-card.php
> +                $photo_url = get_template_directory_uri() . '/assets/images/defaults/person-avatar-default-small.png';
:eyes:

2024-12-04 17:48 UTC, ponsfrilus commented on frontend/epfl-people/templates/dynamic-card.php
> +        // Adding class container
:eyes:

2024-12-04 17:48 UTC, ponsfrilus approved these changes
LGTM, but maybe mention [WPN-166](https://go.epfl.ch/WPN-166)?

2024-12-05 11:37 UTC, jdelasoie requested changes

2024-12-05 11:37 UTC, jdelasoie commented on package.json
> +	"version": "2.40.0",
```suggestion
	"version": "2.41.0",
```

2024-12-05 11:37 UTC, jdelasoie commented on frontend/epfl-google-forms/controller.php
> +    if($url_host == null || preg_match('/\.google\.com$/', $url_host) !== 1)
Pour des questions de lisibilité, je préfère ce format. 
A ta discrétion.
```suggestion
    if (
        $url_host == null ||
        preg_match('/\.google\.com$/', $url_host) !== 1
    )
```

2024-12-05 11:37 UTC, jdelasoie commented on frontend/lib/utils.php
> +        $sanitized_value = preg_replace_callback('(\'|")', function($x) { return htmlentities($x[0], ENT_QUOTES); }, $value ?? '');
Lisibilité
```suggestion
        $sanitized_value = preg_replace_callback(
            '(\'|")',
            function($x) {
                return htmlentities($x[0], ENT_QUOTES);
            },
            $value ?? '');
```

2024-12-22 11:29 UTC, ponsfrilus commented on frontend/epfl-memento/templates/listing_with_the_first_highlighted_event.php
Not sure about `?->` in PHP.

2024-12-22 11:30 UTC, ponsfrilus reviewed
@rosamaggi Not sure about `?->` in PHP: can't find anything in the documentation.

2025-01-03 08:46 UTC, jdelasoie commented
@ponsfrilus 
> @rosamaggi Not sure about `?->` in PHP: can't find anything in the documentation.

What about this ? https://wiki.php.net/rfc/nullsafe_operator

2025-01-06 07:55 UTC, rosamaggi commented on package.json
> +	"version": "2.40.0",
As we won't merge this PR until some site is on OS3, the version of the plugin will still change so I'll edit the version just before the merge with the future correct one.

2025-01-06 21:58 UTC, ponsfrilus commented
> @ponsfrilus
> 
> > @rosamaggi Not sure about `?->` in PHP: can't find anything in the documentation.
> 
> What about this ? https://wiki.php.net/rfc/nullsafe_operator

So it targets PHP 8.0, I would recommend something more "portable".

2025-02-04 16:17 UTC, ponsfrilus approved these changes
If splitting hairs was required, I would tell that `if(` should become `if (`.

2025-03-21 15:00 UTC, ponsfrilus commented on frontend/epfl-people/controller.php
> +    // copy the first unit in order of 'ordre' as main_unit
The rest of the file use 4 spaces for indentation.

2025-03-21 15:03 UTC, ponsfrilus commented on frontend/epfl-hero/view.php
> +	    $array = explode("/", $video_url);
Indent

2025-04-11 13:10 UTC, rosamaggi commented on package.json
> +	"version": "2.40.0",
The current version in master branch is 2.39.0
Why you whould like me to change it to 2.41.0?

2025-04-15 13:24 UTC, rosamaggi commented on package.json
> +	"version": "2.40.0",
DONE: 2.41.1

2025-04-15 13:49 UTC, merged